### ISSUE TITLE
Reloading home page after login fails

### ISSUE THREAD

**Issue by strtw** [marcoscannabrava/free-covid-consultation-calendar#12]
# Bug report

**What is the current behavior?**
Login in succeeds, but reloading the home page results in blank page. 
**If the current behavior is a bug, please provide the steps to reproduce.**
See above. 

**What is the expected behavior?**
reload should show same state of app

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by marcoscannabrava** [comment]
Fixed on last commit
